# English is the default language
defaultContentLanguage = "hu"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= true
# Page settings
baseURL = ""
# languageCode = "en-us"
#theme = ""
copyright = "Everything is mine"

[params]
  custom_css = ["css/custom.css", "css/flags.css"]
  # Meta
  author = "OnBased Group"
  description = "Mi látunk téged"
  email = "info@onbased.com"

[languages]

#######################################################################
# Magyar
#######################################################################

[languages.hu]
  languageCode = "hu"
  title = "OnBased | Mi látunk téged"
  weight = 3

# Cookie Consent
[languages.hu.cookieconsent]
  text = "Ez a weboldal cookie-kat (sütiket) használ azért, hogy weboldalunk használata során a lehető legjobb élményt tudjuk biztosítani."
  link = "Részletek"
  dismiss = "Elfogadom"

# Navigation
[languages.hu.navigation]
  brand = ""
  home = "Kezdőlap"
  # techs = "Technológiák"
  # prices = "App árak"
  # services = "Szolgáltatások"
  about = "Rólunk"
  contact = "Kapcsolat"
  # cta = "Hívjon!"
  
# Hero section
[languages.hu.hero]
  cookie = "Ez a weboldal cookie-kat (sütiket) használ azért, hogy weboldalunk használata során a lehető legjobb élményt tudjuk biztosítani."
  title1 = "Mi látunk téged"
  title2 = "Engedd hogy segítsünk"
  callforactionLink = "mailto:marketing@onbased.com"
  callforactionCaption = "Beszéljünk az Ön projektjéről"

[languages.hu.intro]
  title = "A mi cégünk"
  description = "2008 óta foglalkozunk szoftverek tervezésével, valamint fejlesztéssel, az ebből szerzett tapasztalatok sikeres alapként szolgáltak egy új szolgáltatás, a mobil applikáció fejlesztés kiépítésében. Pontosan tudjuk, hogy egyre fontosabb szerepet töltenek be a mobil eszközök, és ezekre az eszközökre történő alkalmazásfejlesztés is."
  
[[languages.hu.intro.item]]
  title = "Web & Mobil Fejlesztés"
  url = "Service_Web"
  icons = [ "icon-screen-desktop", "icon-screen-smartphone" ]
  color = "#30231d"

[[languages.hu.intro.item]]
  title = "Tanácsadás"
  url = "Service_Consulting"
  icons = [ "icon-layers" ]
  color = "#30231d"

[[languages.hu.intro.item]]
  title = "Backend"
  url = "Service_Backend"
  icons = [ "icon-wrench" ]
  color = "#30231d"


[languages.hu.techs]
  enable = "True"
  title="Technológiák, amiket használunk"
[[languages.hu.techs.tech]]
  alt = "Flutter"
  img = "techs/flutter.svg"
  description = "<p><b>Flutter</b></p>Native Performance<br/>Fast Development<br/>Expressive & Flexible UI"
  link="https://www.flutter.dev"
[[languages.hu.techs.tech]]
  alt = "Apollo"
  img = "techs/apollo.svg"
  description = "<p><b>Apollo</b></p>Ultra-flexible, community driven GraphQL client for React, JavaScript, and native platforms"
  link="https://www.apollographql.com"
[[languages.hu.techs.tech]]
  alt = "Bootstrap"
  img = "techs/bootstrap.svg"
  description = "<p><b>Bootstrap</b></p>The world's most popular responsive and mobile-first front-end component library"
  link="https://getbootstrap.com/"
[[languages.hu.techs.tech]]
  alt = "Azure"
  img = "techs/azure.svg"
  description = "<p><b>Azure</b></p>Building, testing, deploying, and managing applications and services in the cloud"
  link="https://azure.microsoft.com"
[[languages.hu.techs.tech]]
  alt = "Django & Python"
  img = "techs/django_python.svg"
  description = "<p><b>Django + Python</b></p>High-level Python Web framework that encourages rapid development and clean, pragmatic design."
  link="https://www.djangoproject.com"
[[languages.hu.techs.tech]]
  alt = "Docker"
  img = "techs/docker.svg"
  description = "<p><b>Docker</b></p>Platform for developers and sysadmins to build, ship, and run distributed applications, whether on laptops, data center VMs, or the cloud"
  link="https://www.docker.com"
[[languages.hu.techs.tech]]
  alt = "Elasticsearch & Logstash & Kibana"
  img = "techs/elastic_logstash_kibana.svg"
  description = "<p><b>Elasticsearch + Logstash + Kibana</b></p>Effiective combination to store, find and display logs"
  link="https://www.elastic.co"
[[languages.hu.techs.tech]]
  alt = "Firebase"
  img = "techs/firebase.svg"
  description = "<p><b>Firebase</b></p>Google's mobile platform that helps you quickly develop high-quality apps and grow your business."
  link="https://firebase.google.com"
[[languages.hu.techs.tech]]
  alt = "GrapgQL"
  img = "techs/graphql.svg"
  description = "<p><b>GraphQL</b></p>New way to query your data. Write queries, not code"
  link="http://graphql.org"
[[languages.hu.techs.tech]]
  alt = "Kubernetes"
  img = "techs/kubernetes.svg"
  description = "<p><b>Kubernetes</b></p>Production-Grade Container Orchestration which builds upon 15 years of experience of running production workloads at Google"
  link="https://kubernetes.io"
[[languages.hu.techs.tech]]
  alt = "RabbitMQ"
  img = "techs/rabbitmq.svg"
  description = "<p><b>RabbitMQ</b></p>The most widely deployed open source message broker"
  link="https://www.rabbitmq.com"
[[languages.hu.techs.tech]]
  alt = "Spring"
  img = "techs/spring.svg"
  description = "<p><b>Spring</b></p>Provides a comprehensive programming and configuration model for modern Java-based enterprise applications"
  link="https://spring.io"

# Services section
[languages.hu.services]
  enable = true
  title = "Szolgáltatások"
  description = "Szeretnénk tapasztalatainkat Önnel is megosztani"
  background = "backgrounds/services.png"

[[languages.hu.services.item]]
  title = "Web &amp; Mobil Fejlesztés"
  name = "Service_Web"
  description = "7.4 milliárd ember él a Földön, 5.7 milliárd rendelkezik közülük mobiltelefonnal, amelyek egyre nagyobb része okostelefon. Egy, a közelmúltban megjelent Pew Research Center tanulmány szerint, a telefonjaikon internetet használó felhasználók száma több mint megduplázódott az elmúlt 5 évben, ahogy a mobilalkalmazásokat használók száma is. Hisszük, hogy a jövőben ezek a számok még tovább fognak növekedni és megoldásainkkal szeretnénk kényelmesebbé, jobbá tenni ezen eszközök használatát."
  icons = [ "icon-screen-desktop", "icon-screen-smartphone" ]
[[languages.hu.services.item]]
  title = "Tanácsadás"
  name = "Service_Consulting"
  description = "Készen állunk, hogy technológiai partnerévé váljunk és segítsünk megvalósítani a projektjét, az Ön igényei alapján."
  icons = [ "icon-layers" ]
[[languages.hu.services.item]]
  title = "Backend"
  name = "Service_Backend"
  description = "Megoldásainkat légitársaságok, repterek és légiforgalom irányító társaságok döntő fontosságú környezetekben használják évek óta. Az elmúlt több mint 10 évben németországi partnerünkön keresztül Európa egyik legnagyobb légitársaságának fejlesztettünk elsősorban reporting és törzsadatkezelő (Master Data Management), valamint nagy rendelkezésre állású Data Hub rendszereket. Az általunk elkészített szoftverek a mai napig szerves részét képezik a légitársaság mindennapi működésének."
  icons = [ "icon-wrench" ]


# Prices section
[languages.hu.prices]
  enable = true
  title = "Applikáció készítési csomagajánlataink"
  # description = "Do you need mobile application for your business or even for yourself?"
  background = "backgrounds/prices.png"
  cta = '<a href="tel: +36 30 559 1118" target="_blank">Hívjon</a>'

[[languages.hu.prices.package]]
  title = "Basic"
  price = "490.000"
  currency = "Ft"
  features = [
    "Applikáció fejlesztés Android és iOS rendszerekre",
    "Natív funkciók",
    "Maximum 10 funkció vagy oldal",
    "Applikáció feltöltése a Google Play és iTunes Connect áruházakba",
  ]

[[languages.hu.prices.package]]
  highlighted = true
  title = "Standard"
  price = "890.000"
  currency = "Ft - TÓL"
  features = [
    "Applikáció fejlesztés Android és iOS rendszerekre",
    "Natív funkciók",
    "Maximum 10 funkció vagy oldal",
    "Applikáció feltöltése a Google Play és iTunes Connect áruházakba",
    "1 óra szakmai tanácsadás"
  ]

[[languages.hu.prices.package]]
  title = "Prémium"
  price = "Egyedi ár"
  currency = ""
  features = [
    "Applikáció fejlesztés Android és iOS rendszerekre",
    "Natív funkciók",
    "Maximum 20 funkció vagy oldal",
    "Applikáció feltöltése a Google Play és iTunes Connect áruházakba",
    "2 óra szakmai tanácsadás",
    "Egyszerű adminisztrációs felület",
    "Egyedi UX/UI dizájn",
    "Egyedi App ikonok és splash screen-ek"
  ]

# [[languages.hu.prices.package]]
#   name = "enterprise"
#   title = "Enterprise"
#   price = "Call us"
#   cta = "Call"
#   features = []

# About section
[languages.hu.about]
  enable = true
  title = "Rólunk"
  description = "Találkozni - jó kezdet. Nem elválni - haladás. Hosszútávon együtt dolgozni - siker.” - Henry Ford"

[[languages.hu.about.item1]]
  name = "Albert Papp"
  position = "Társalapító & CEO & Ügyfél Kapcsolattartó"
  description = "A gazdasági sikereket nem egy ember éri el, hanem a csapat."
  img = "team/albert_papp.jpg"
  alt = "Albert Papp"
  social = [
    ["icon-linkedin", "https://linkedin.com/in/albert-papp"],
    ["icon-facebook", "https://facebook.com/albert.papp.75"],
    ["icon-github",   "https://github.com/palbert75"]
   # ["icon-twitter",  "https://twitter.com/albert_m_papp"]
  ]

[[languages.hu.about.item1]]
  name = "Ákos Belákovics"
  position = "Társalapító & Senior Full Stack Szoftverfejlesztő"
  description = "Elhivatottság és tapasztalat, amelyek segítenek az olyan integrált szoftverrendszerek fejlesztéseben, amelyek megfelelnek az ipari szabványoknak."
  img = "team/akos_belakovics.jpg"
  alt = "Ákos Belákovics"
  social = [
    ["icon-linkedin", "https://linkedin.com/in/akos-belakovics"],
    ["icon-facebook", "https://facebook.com/akos.belakovics"],
    ["icon-github", "https://github.com/defned"]
    #["icon-twitter", "https://twitter.com/AkosBelakovics"]
  ]

# Counters section
[languages.hu.counters]
  enable = true
  title = "Statisztikák"
  background = "backgrounds/counters.png"

[[languages.hu.counters.item]]
  description = "Átadott Projekt"
  icon = "icon-briefcase"
  from = 0
  to = 43
  interval = 50
  speed = 5000

[[languages.hu.counters.item]]
  description = "Kódsor"
  icon = "icon-code"
  from = 0
  to = 1343409
  interval = 50
  speed = 5000

[[languages.hu.counters.item]]
  description = "Csésze Kávé"
  icon = "icon-cup"
  from = 0
  to = 1302
  interval = 50
  speed = 5000

# Kapcsolat
[languages.hu.contact]
  enable = true
  map = true
  form = true
  title = "Kapcsolat"
  socialTitle = "Kövessen minket"
  details = [
    ["icon-home", "2800 Tatabanya Ibolya utca 12.<br/>Magyarország"],
    ["icon-phone", '<a href="tel: +36 30 559 1118" target="_blank">+36 30 559 1118</a>'],
    ["icon-envelope", '<span itemprop="telephone"><a href="mailto:info@onbased.com" target="_blank">info@onbased.com</a></span>'],
    ["icon-globe", '<a href="https://onbased.com" target="_blank">onbased.com</a>']
  ]
  name = "Név"
  email = "Email"
  phone = "Telefon"
  message = "Üzenet"
  button = "Küldés"

[languages.hu.footer]
  enable = true
  copyright = '&copy; OnBased Group Kft. Minden jog fenntartva. <br>Készítette <a href="#">onbased.com</a>'
  links = [
    ["icon-twitter", "https://twitter.com/onbasedIT"],
    ["icon-facebook", "https://facebook.com/onbasedit"],
    ["icon-linkedin", "https://facebook.com/onbasedit"],
    ["icon-github", "https://facebook.com/onbasedit"],
    ["icon-instagram", "https://facebook.com/onbasedit"]
  ]
