# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= false
# Page settings
baseURL = ""
# languageCode = "en-us"
#theme = ""
copyright = "Everything is mine"

[params]
  custom_css = ["css/custom.css", "css/flags.css"]
  # Meta
  author = "OnBased Group"
  description = "Software engineering and consulting at the highest level"
  email = "info@onbased.com"

[languages]
[languages.en]
  languageCode = "en"
  title = "We see your vision"
  weight = 1

# Cookie Consent
[languages.en.params]
  welcome = "Welcome"
  home = "Home"

[languages.en.params.cookieconsent]
  text = "This website uses cookies to ensure you get the best experience on our website."
  link = "Learn more"
  dismiss = "Accept"

# Navigation
[languages.en.params.navigation]
  brand = ""
  home = "Home"
  techs = "Technologies"
  prices = "App prices"
  services = "Services"
  showcases = "Showcases"
  about = "About"
  contact = "Contact"

# Hero section
[languages.en.params.hero]
  title1 = "OnBased Group"
  title2 = "Your Partner in Aviation Data Mastery"
  title3 = ""
  subtitle = "We are ready for our next journey"
  keyword = [ "Write.", "Less.", "Code." ]
  callforactionTitle = "Achieving Balance and Stability"
  callforactionLink = "mailto:info@onbased.com"
  callforactionCaption = "Let's talk about your Project"
  background = "backgrounds/header.png"

# Intro section
# Available icons: http://simplelineicons.com/
[languages.en.params.intro]
  title = "Our company"
  description = "Since 2004, we have specialized in data integration and engineering, building a strong foundation in designing and managing complex data systems. Over the years, our expertise has evolved to meet the demands of modern industries, with a primary focus on leveraging cutting-edge cloud technologies. Today, we deliver tailored data solutions that empower businesses to streamline operations, harness real-time insights, and achieve scalable growth."

[[languages.en.params.intro.item]]
  title = "Software Engineering"
  url = ""
  image = [ "/images/badges/development.png" ]

#[[languages.en.params.intro.item]]
#  title = "Consulting"
#  url = "Service_Consulting"
#  image = [ "/images/badges/consulting.png" ]

[[languages.en.params.intro.item]]
  title = "Data Engineering"
  url = ""
  image = [ "/images/badges/marketing.png" ]

[languages.en.params.mission]
  title = "Our Mission"
  description = "At OnBased Group, we transform complex data into actionable insights. By leveraging innovation and cutting-edge technologies, we empower businesses to optimize operations, enhance decision-making, and unlock their full potential."

[languages.en.params.values]
  title = "Our Special Sauce"
  description = "Our unique blend of industry expertise, cutting-edge technology, and process-driven insights enables us to deliver tailored, reliable, and impactful data solutions for aviation and beyond."

[[languages.en.params.values.item]]
  title = "Innovation"
  image = [ "/images/badges/innovation.png" ]

[[languages.en.params.values.item]]
  title = "Perfection"
  image = [ "/images/badges/perfection.png" ]

[[languages.en.params.values.item]]
  title = "Execution"
  image = [ "/images/badges/execution.png" ]

[[languages.en.params.values.item]]
  title = "Clarity"
  image = [ "/images/badges/clarity.png" ]

[[languages.en.params.values.item]]
  title = "Honesty"
  image = [ "/images/badges/honesty.png" ]

[[languages.en.params.values.item]]
  title = "Service"
  image = [ "/images/badges/service.png" ]

[languages.en.params.showcases]
  title = "Showcases"
  enable = true
  description = "Description goes here"

[[languages.en.params.showcases.item]]
  title = "Medallion Architecture Data Pipeline"
  url = "showcases/medallion_architecture_data_pipeline/"
  image = "/images/badges/service.png"

[languages.en.params.techs]
  enable = "True"
  title="Technologies we use"

# Services section
[languages.en.params.services]
  enable = true
  title = "Services"
  description = "We would like to share our experience with you"
  background = "backgrounds/services.png"

[[languages.en.params.services.item]]
  title = "Data Integration & Engineering"
  name = "Service_Backend"
  description = "Centralize and harmonize data from diverse aviation systems with real-time streaming and batch processing capabilities."
  image = [ "/images/badges/backend.png" ]

[[languages.en.params.services.item]]
  title = "Cloud Solutions"
  name = "Service_Web"
  description = "Leverage Azure Cloud and Databricks for scalable and secure data solutions tailored to aviation needs."
  image = [ "/images/badges/development.png" ]

[[languages.en.params.services.item]]
  title = "API Development"
  name = "Service_Web"
  description = "Enable seamless data access and integration through Kubernetes-based Flask APIs."
  image = [ "/images/badges/honesty.png" ]

[[languages.en.params.services.item]]
  title = "Consulting"
  name = "Service_Consulting"
  description = "Deliver tailored software solutions designed to meet the unique requirements of your project."
  image = [ "/images/badges/execution.png" ]

# About section
[languages.en.params.about]
  enable = true
  title = "About"
  description = "We bring ideas to life by combining years of experiences of our very creative team."

[[languages.en.params.about.item1]]
  name = "Albert Papp"
  position = "Founder"
  description = "Great things in business are never done by one person. They're done by a team of people."
  img = "team/albert_papp.jpg"
  alt = "Albert Papp"
  social = [
    ["icon-linkedin", "https://linkedin.com/in/albert-papp"],
    ["icon-facebook", "https://facebook.com/albert.papp.75"],
    ["icon-github",   "https://github.com/palbert75"]
  #  ["icon-twitter",  "https://twitter.com/albert_m_papp"]
  ]

[[languages.en.params.about.item1]]
  name = "Ákos Belákovics"
  position = "Founder"
  description = "I am passionate about building integrated software systems which are fit to the industrial standards."
  img = "team/akos_belakovics.jpg"
  alt = "Ákos Belákovics"
  social = [
    ["icon-linkedin", "https://linkedin.com/in/akos-belakovics"],
    ["icon-facebook", "https://facebook.com/akos.belakovics"],
    ["icon-github", "https://github.com/defned"]
  # ["icon-twitter", "https://twitter.com/AkosBelakovics"]
  ]

# Counters section
[languages.en.params.counters]
  enable = true
  title = "Stats"

[[languages.en.params.counters.item]]
  description = "Delivered projects"
  icon = "icon-briefcase"
  from = 0
  to = 28
  interval = 50
  speed = 5000

[[languages.en.params.counters.item]]
  description = "Lines of code"
  icon = "icon-code"
  from = 0
  to = 1012307
  interval = 50
  speed = 5000

[[languages.en.params.counters.item]]
  description = "Cups of coffee"
  icon = "icon-cup"
  from = 0
  to = 1102
  interval = 50
  speed = 5000

# Contact section
[languages.en.params.contact]
  enable = true
  map = false
  form = true
  title = "Let's work together"
  description = "Get in touch"
  socialTitle = "Follow us"
  details = [
    ["icon-home", "1066 Budapest Dessewffy u. 18-20. </br>Hungary"],
    ["icon-phone", '<a href="tel: +36 30 559 1118" target="_blank">+36 30 559 1118</a>'],
    ["icon-envelope", '<span itemprop="telephone"><a href="mailto:info@onbased.com" target="_blank">info@onbased.com</a></span>'],
    ["icon-globe", '<a href="https://onbased.com" target="_blank">onbased.com</a>']
 ]
  name = "Name"
  email = "Email"
  phone = "Phone"
  message = "Message"
  button = "Send message"

# Footer section
[languages.en.params.footer]
  enable = true
  copyright = '&copy; OnBased Group Kft. All Rights Reserved. <br>Created by <a href="#">onbased.com</a>'
  links = [
    #["icon-twitter", "https://twitter.com/onbasedIT"],
    #["icon-facebook", "https://facebook.com/onbasedit"],
    #["icon-linkedin", "https://facebook.com/onbasedit"],
    ["icon-github", "https://github.com/onbased"],
    #["icon-instagram", "https://facebook.com/onbasedit"]
  ]
