[context.production.environment]
  HUGO_VERSION = "0.55.4"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.4"

[build]
  command = "pushd themes/onbased-it-theme; npm install -g autoprefixer; npm install -g postcss-cli; npm install; popd; hugo --gc --minify --baseURL https://it.onbased.com --destination public --i18n-warnings --verbose"
  publish = "public/"

