[context.production.environment]
  HUGO_VERSION = "0.136.1"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.136.1"

[build]
  command = "hugo --gc --minify --baseURL https://onbased.com --destination public --verbose"
  publish = "public/"
